global:
  scrape_interval: 15s #15 snde bir metrikleri güncelle
  evaluation_interval: 15s # kurallar için
rule_files:

scrape_configs:
  - job_name: "FILTER-SERVICE"
    scrape_interval: 2s
    metrics_path: "/FILTER-SERVICE/actuator/prometheus"
    static_configs:
      - targets: ['localhost:9010']
  - job_name: "MAINTENANCE-SERVICE"
    scrape_interval: 2s
    metrics_path: "/MAINTENANCE-SERVICE/actuator/prometheus"
    static_configs:
      - targets: [ 'localhost:9010' ]
  - job_name: "INVENTORY-SERVICE"
    scrape_interval: 2s
    metrics_path: "/INVENTORY-SERVICE/actuator/prometheus"
    static_configs:
      - targets: [ 'localhost:9010' ]
  - job_name: "PAYMENT-SERVICE2"
    scrape_interval: 2s
    metrics_path: "/PAYMENT-SERVICE2/actuator/prometheus"
    static_configs:
      - targets: [ 'localhost:9010' ]