spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/inventory-db
    password: '123456'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: update