spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        default-label: main
        git:
          uri: https://github.com/MERVECETIN1929/config-server-t2
server:
  port: 8888
